INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (1,1,'Home','Home','View Job Status','null');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (2,1,'Preparation','Buildout view','View Buildouts','null');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (3,1,'Preparation','Inventory view','View Inventories','null');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (4,1,'Preparation','Part Selection view','View Part List','null');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (5,1,'Preparation','Part Selection view','Download to excel','null');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (6,1,'Preparation','Part Selection view','Select parts and Add to inventory','null');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (7,1,'Preparation','Part Selection view','Save','null');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (8,1,'Preparation','Part Selection view','Delete','null');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (9,1,'Preparation','Part Selection view','Line Side Verification Sheet','null');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (10,1,'Preparation','Part Selection view','Inv Sheet','null');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (11,1,'Preparation','Part Selection view','Duplicates','null');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (12,1,'Preparation','Part Selection view','Missing Parts','null');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (13,1,'Preparation','Part Selection view','Check Attachment Point','null');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (14,1,'Preparation','Part Selection view','Check for updates','New additions');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (15,1,'Preparation','Part Selection view','Check for updates','To be excluded');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (16,1,'Preparation','Part Selection view','Check for updates','Not LC2 in other docks');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (17,1,'Preparation','Part Selection view','Check for updates','Address Updates');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (18,1,'Preparation','Part Selection view','Check for updates','Other Address Updates');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (19,1,'Parts Input','Input view','View Part List','null');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (20,1,'Parts Input','Input view','Safety','null');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (21,1,'Parts Input','Input view','Overflow','null');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (22,1,'Parts Input','Input view','Non-vehicle','null');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (23,1,'Parts Input','Input view','Counts input','Inventory count');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (24,1,'Parts Input','Input view','Counts input','Pending countsheet');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (25,1,'Parts Input','Input view','Counts input','ALC snapshot');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (26,1,'Parts Input','Input view','Counts input','Body Num Errors');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (27,1,'Parts Input','Input view','Counts input','Discrepancies');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (28,1,'Parts Input','Input view','Counts input','Finalize');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (29,1,'Parts Input','Input view','In-Transit','NA pipeline input');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (30,1,'Parts Input','Input view','In-Transit','OS container input');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (31,1,'Parts Input','Input view','In-Transit','Broadcast intransit input');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (32,1,'Parts Input','Input view','In-Transit','NA Last orders');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (33,1,'Parts Input','Input view','In-Transit','Get NA & OS intransit');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (34,1,'Parts Input','Input view','In-Transit','View TMC pipeline');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (35,1,'Parts Input','Input view','OSC','Add New');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (36,1,'Parts Input','Input view','OSC','Delete');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (37,1,'Parts Input','Input view','OSC','Get Details');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (38,1,'Parts Input','Input view','Unit Only','Gentani');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (39,1,'Parts Input','Input view','Unit Only','Line inventory');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (40,1,'Parts Input','Input view','Unit Only','Units remaining');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (41,1,'Parts Input','Input view','Unit Only','Initial requirements');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (42,1,'Calculation','On demand calculation','View Parts with Results','Download to excel');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (43,1,'Calculation','On demand calculation','Check errors','Acknowledge errors');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (44,1,'Calculation','On demand calculation','Check errors','Download to excel');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (45,1,'Calculation','On demand calculation','Perform Calculation & Save Initial Countdown','null');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (46,1,'Calculation','On demand calculation','Adjustments','null');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (47,1,'Calculation','On demand calculation','Filter Parts','null');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (48,1,'Calculation','On demand calculation','Save Active Countdown','null');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (49,1,'Calculation','On demand calculation','Check comparison report','Download to excel');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (50,1,'Calculation','Piece count','null','null');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (51,1,'Calculation','Supplier Communication','null','null');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (52,1,'Calculation','Requirement check','Inquire requirement check','null');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (53,1,'Calculation','Requirement check','ALC snapshot','null');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (54,1,'Reports','Active countdown results','View results','null');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (55,1,'Reports','Active countdown results','Delete Countdown','null');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (56,1,'Reports','Active countdown results','Adjustments','null');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (57,1,'Reports','Active countdown results','Save','null');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (58,1,'Reports','Active countdown results','Download to excel','null');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (59,1,'Reports','Archive countdown','View results','null');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (60,1,'Reports','Archive countdown','Download to excel','null');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (61,1,'System maintenance','Inventory group setup','null','null');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (62,1,'System maintenance','Partial piece setup','null','null');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (63,1,'System maintenance','Supplier setup','null','null');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (64,1,'System maintenance','Dock shop setup','null','null');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (65,1,'System maintenance','Obsolescence view','null','null');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (66,1,'System maintenance','Parts Information Setup','null','null');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (67,1,'System maintenance','Scrap flag update','null','null');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (68,1,'System maintenance','GALC snapshot','null','null');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (69,1,'System maintenance','Supplier Email Archive','null','null');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (70,1,'System maintenance','IS Monitoring','null','null');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (71,2,'Rundown','Single Part','Get Rundown','null');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (72,2,'Rundown','Single Part','Counter checkbox','null');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (73,2,'Multipart','Multipart','Add New Parts ','List Parts');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (74,2,'Multipart','Multipart','Add New Parts ','Add Parts');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (75,2,'Multipart','Multipart','Enter Last Delivery','null');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (76,2,'Multipart','Multipart','Export to Excel','null');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (77,2,'Multipart','Multipart','Counter checkbox','null');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (78,2,'Multipart','Multipart','Get Rundown','null');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (79,2,'Multipart','Multipart','Save','null');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (80,2,'Multipart','Multipart','Delete','null');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (81,2,'Multipart','Multipart','Mass upload','null');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (82,2,'Reports','Reports','Fetch ','null');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (83,2,'Reports','Reports','Print to Pdf','null');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (84,2,'Reports','Reports','Export All parts Rundown','null');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (85,2,'Reports','Reports','Upload Tab/Adjustment','null');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (86,2,'Reports','Reports','Export to Excel','null');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (87,2,'Reports','Reports','Save Results','null');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (88,2,'Reports','Reports','Hyperlinks','Search');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (89,2,'Reports','Reports','Hyperlinks','Sort');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (90,2,'Reports','Reports','Hyperlinks','Export to Excel');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (91,2,'Admin Console','Configure Counters','Add new Counter','null');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (92,2,'Admin Console','Configure Counters','Update','null');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (93,2,'Admin Console','Configure Counters','Delete','null');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (94,2,'Admin Console','Configure Counters','Export to Excel','null');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (95,2,'Admin Console','MinMax Inventory Setup','Add new','null');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (96,2,'Admin Console','MinMax Inventory Setup','Update','null');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (97,2,'Admin Console','MinMax Inventory Setup','Report- Removable Parts','Delete');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (98,2,'Admin Console','MinMax Inventory Setup','Report- Removable Parts','Export to Excel');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (99,2,'Admin Console','MinMax Inventory Setup','Report- Removable Parts','Search');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (100,2,'Admin Console','MinMax Inventory Setup','Report- Removable Parts','Sort');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (101,2,'Admin Console','MinMax Inventory Setup','Mass upload','null');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (102,2,'Admin Console','MinMax Inventory Setup','Export to Excel','null');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (103,2,'Home Page','Home ','Hyperlink - Request ID','Completed - View');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (104,2,'Home Page','Home ','Hyperlink - Request ID','Not Submitted - All Multipart screen function');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (105,2,'Home Page','Home ','Hyperlink - Request ID','In progress - Cancel');
INSERT INTO tmm.ccs_actions(action_id,module_id, menu_item, screen, function, sub_function)VALUES (106,1,'Preparation','Part Selection view','Check for updates','Line Group Changes');
