INSERT INTO tmm.ccsb_jobs(job_code, job_description)VALUES('CCS_STKOCON','Load Overseas Container data');
INSERT INTO tmm.ccsb_jobs(job_code, job_description)VALUES('CCS_STKOPRT','Load Overseas Parts data');
INSERT INTO tmm.ccsb_jobs(job_code, job_description)VALUES('CCS_STKOTMC','Load Overseas TMC data');
INSERT INTO tmm.ccsb_jobs(job_code, job_description)VALUES('CCS_OTHER_ADDR','Load Other Address data for Parts');
INSERT INTO tmm.ccsb_jobs(job_code, job_description)VALUES('CCS_ORUIF','Load ORUIF data');
INSERT INTO tmm.ccsb_jobs(job_code, job_description)VALUES('CCS_BCDIF','Generate BCDIF data');
INSERT INTO tmm.ccsb_jobs(job_code, job_description)VALUES('CCS_CL_CD','Load CL/CD delta');
INSERT INTO tmm.ccsb_jobs(job_code, job_description)VALUES('CCS_REMOVE_VEHICLE_SOLD','Delete last 7 days Vehicle Sold data');
INSERT INTO tmm.ccsb_jobs(job_code, job_description)VALUES('CCS_REMOVE_VEHICLE','Delete already sold Vehicle data');
INSERT INTO tmm.ccsb_jobs(job_code, job_description)VALUES('CCS_REMOVE_EXPIRED_BUILDOUTS','Delete Buildouts whose end data have passed');
INSERT INTO tmm.ccsb_jobs(job_code, job_description)VALUES('CCS_SERVICE_PARTS','Load Service Parts data');
INSERT INTO tmm.ccsb_jobs(job_code, job_description)VALUES('CCS_NQC_SUMMARY','Load PASS NQC Summary data');
INSERT INTO tmm.ccsb_jobs(job_code, job_description)VALUES('CCS_PASS_VEHICLE','Load PASS Vehicle data');
INSERT INTO tmm.ccsb_jobs(job_code, job_description)VALUES('CCS_FAMILY_CODES','Load Family Codes data');
INSERT INTO tmm.ccsb_jobs(job_code, job_description)VALUES('CCS_DETAILED_NQC','Load Detailed NQC data');
INSERT INTO tmm.ccsb_jobs(job_code, job_description)VALUES('CCS_PURLGST','Purge and Load PURLGST NA Pipe data');
INSERT INTO tmm.ccsb_jobs(job_code, job_description)VALUES('CCS_PURORDR','Purge and Load PURORDR NA Pipe data');
INSERT INTO tmm.ccsb_jobs(job_code, job_description)VALUES('CCS_PURORDR_ADD','Load PURORDR NA Pipe data');
INSERT INTO tmm.ccsb_jobs(job_code, job_description)VALUES('CCS_PURORDR_DEL','Delete PURORDR NA Pipe data');
INSERT INTO tmm.ccsb_jobs(job_code, job_description)VALUES('CCS_PURITEM','Purge and Load PURITEM NA Pipe data');
INSERT INTO tmm.ccsb_jobs(job_code, job_description)VALUES('CCS_PURITEM_ADD','Load PURITEM NA Pipe data');
INSERT INTO tmm.ccsb_jobs(job_code, job_description)VALUES('CCS_PURITEM_DEL','Delete PURITEM NA Pipe data');
INSERT INTO tmm.ccsb_jobs(job_code, job_description)VALUES('CCS_ARDBGSNP','ARDB Snapshot Data Load');
INSERT INTO tmm.ccsb_jobs(job_code, job_description)VALUES('CCS_ARDBVECL','ARDB Vehicle Data Load');
INSERT INTO tmm.ccsb_jobs(job_code, job_description)VALUES('CCS_EKANBAN_LAST_ORD_CALC_DT','E-Kanban Order Updates - Last Order Calc Date');
INSERT INTO tmm.ccsb_jobs(job_code, job_description)VALUES('CCS_NAPIPE_LAST_ORD_CALC_DT','NA Pipeline - Last Order Calc Date');
INSERT INTO tmm.ccsb_jobs(job_code, job_description)VALUES('CCS_GALC_SNAPSHOT_SUSP','GALC Snapshot Suspension');
INSERT INTO tmm.ccsb_jobs(job_code, job_description)VALUES('CCS_IS_MON_EMAIL_TRIGGER','Switch IS Monitoring On / Off');
INSERT INTO tmm.ccsb_jobs(job_code, job_description)VALUES('CCS_ARDBSUSP','ARDB Job Suspension');
INSERT INTO tmm.ccsb_jobs(job_code, job_description)VALUES('CCS_POPULATE_REF_NO','Populate Ref No for Detailed NQC data');