### Major Input Variables are defined here.
---

#######Required input variables##########
appID: ccs
appName: fod-interface
createdByEmail: mayukh.ray@toyota.com
accountType: nonprod
accountId: 801624696547
costCenter: 955042
region: us-west-2
environment: qa
runtime: nodejs16.x
#kmsKeyArn: 
#deploymentBucketName: 

########Optional#################
VPCPresent: YES #Change to YES, if needed
frameworkVersion: default

###########Version Config
versionFunctions: false

###########IAM
#iamrole: IamRoleLambdaExecution #Default IAM role.
CustomIAMPresent: NO #Change to YES, if needed

###########Dead-Letter-Queue
DLQ: null #Default Value
DLQPresent: NO #Change to YES, if needed

###########RDS Config
DBSecretArn: arn:aws:secretsmanager:us-west-2:801624696547:secret:ccs-qa-db-details-cBiMQP

########### Events Config
S3BucketName: ccs-qa-data-files
